version: '3.4'

services:
  containerizedapi:
    image: ${DOCKER_REGISTRY-}containerizedapi
    build:
      context: .
      dockerfile: ContainerizedAPI/Dockerfile

  redis:
    image: redis
    ports:
      - "56379:6379"